# ./.tmuxinator.yml

name: fire-archmage-blog
root: ./

windows:
  - editor:
      layout: 6a44,233x54,0,0[233x45,0,0,0,233x8,0,46,2]
      panes:
        - 
        - 
  - server:
      panes:
        - make serve-site
